### ISSUE TITLE
Resource limits don't reflect the nodepool?

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/minio-operator#13]
The MinIO node pool was recently moved to D32, but the resource requests/limits haven't been edited. Should we double these values?

https://github.com/StatCan/minio-operator/blob/cb5596f3639b0c77027c005a657142ccaabbf40d/instances/base/tenant.yaml#L135-L141

CC @zachomedia

**Comment by zachomedia** [comment]
@blairdrummond The node was was decided based on those limits and the fact that we run multiple MinIO instances. So there are 3 MinIO pods per node (standard, premium and hackathon).

**Comment by blairdrummond** [comment]
Makes sense!
