### ISSUE TITLE
Failed to publish the  new custom-built image for minio

### ISSUE THREAD

**Issue by Nancy-Badran** [StatCan/minio-operator#20]
There is two issues: 

- Need to “squash” the layers together, but this doesn’t work on GitHub actions since experimental docker features aren’t enabled. This is due to a “feature” where the operator downloads the executable from the largest layer in the image.
- We need a .sha256sum and .minisign (https://jedisct1.github.io/minisign/) https://github.com/minio/operator/blob/79ff2c294728030a88f29e171dcc96952cbf6bdd/pkg/controller/cluster/main-controller.go#L559. These don’t exist in a custom-built image

Kind environment was required for testing minio-operator with a minio image. Instructions for this setup have been added to the README of this repo.

**Comment by Nancy-Badran** [comment]
we can install minisign , a tool  to sign files and verify signatures, as OSX  binary  from https://github.com/jedisct1/minisign/releases/download/0.9/minisign-osx.zip

**Comment by zachomedia** [comment]
I had to re-open this, unfortunately it looks like in the 4.x line the CRD has changed which doesn't work with our current installation.

**Comment by brendangadd** [comment]
Closing as `wont-fix` as we are moving away from operator.
